 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: atail_100g                                                  
     # Surfaces =   4
     # Strips   = 104
     # Vortices =1840

  Sref = 0.70000E-01   Cref = 0.80000E-01   Bref = 0.85000    
  Xref = 0.61515E-01   Yref =  0.0000       Zref = 0.36177E-02

 Standard axis orientation,  X fwd, Z down         

 Run case: stability zero lift                     

  Alpha =  -1.75265     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02746     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.02592
  CZtot =  -0.19557     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.19631
  CDtot =   0.02147
  CDvis =   0.02000     CDind = 0.0014688
  CLff  =   0.19622     CDff  = 0.0017891    | Trefftz
  CYff  =   0.00000         e =    0.6637    | Plane  

   ruddervator     =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.993811    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.145426
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.047340
 y  mom.  Cm |    Cma =   1.033746    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.018767

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   3.694340    CLr =  -0.000000
 y  force CY |    CYp =  -0.100669    CYq =   0.000000    CYr =   0.063539
 x' mom.  Cl'|    Clp =  -0.508028    Clq =  -0.000000    Clr =   0.049159
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -2.438655    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.020447    Cnq =  -0.000000    Cnr =  -0.010489

                  ruddervator  d01 
                  ----------------
 z' force CL |   CLd01 =   0.005561
 y  force CY |   CYd01 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.000000
 y  mom.  Cm |   Cmd01 =  -0.010031
 z' mom.  Cn'|   Cnd01 =  -0.000000
 Trefftz drag| CDffd01 =  -0.000229
 span eff.   |    ed01 =   0.122345



 Neutral point  Xnp =   0.044955

 Clb Cnr / Clr Cnb  =   0.538223    (  > 1 if spirally stable )
